Fixing YAML

diff --git a/.cloudbees/workflows/main-workflow.yaml b/.cloudbees/workflows/main-workflow.yaml
--- a/.cloudbees/workflows/main-workflow.yaml
+++ b/.cloudbees/workflows/main-workflow.yaml
@@ -160,6 +160,13 @@ jobs:
             | MAJOR_COUNT          | ${{ steps.FetchSonarQubeIssues.outputs.MAJOR_COUNT }} |
             | MINOR_COUNT          | ${{ steps.FetchSonarQubeIssues.outputs.MINOR_COUNT }} |
           format: MARKDOWN
+## Quality gate check
+      - name: Quality gate
+        if: ${{ fromJSON(steps.FetchSonarQubeIssues.outputs.BLOCKER_COUNT) > 0 }} 
+        uses: docker://alpine:3.18
+        run: |
+          echo "Scan gate failed: Unacceptable quality threshold"
+          exit 1
 
   deploy:
     environment: DOW Production
